# Generated by Django 2.2.12 on 2020-05-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modoboa_radicale', '0005_auto_20200220_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedcalendar',
            name='access_token',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='access_token',
            field=models.CharField(max_length=50),
        ),
    ]
